### ISSUE TITLE
I have the same study.

### ISSUE THREAD

**Issue by Student-HXJ** [tomov/Exploration-fMRI-Task#1]
Hi, do you have any idea about how to use these tfMRI data now?

**Comment by tomov** [comment]
Hi, I’m not sure I understand the question. Could you elaborate?

**Comment by Student-HXJ** [comment]
I have the dataset of task fMRI with the filename's suffix is nii.
this is a 4d matrix,  but I don't know what is mean in each dimension. 
The main question is which dimension is representative of the time series.
and I want to use this data file to be as a train data for classification. 
Could you give me some ideas?

**Comment by tomov** [comment]
I believe this should be specified in the file header  – look at the documentation for the niftiread function in Matlab

Momchil Tomov

**Comment by Student-HXJ** [comment]
ok, thank you , I'll have a try
